### ISSUE TITLE
No token generated

### ISSUE THREAD

**Issue by andy-knrd** [i-lateral/silverstripe-checkout-payway#2]
No token is being added to the URL being passed to PayWay.

I get the following error notices
[Notice] Undefined offset: 1
in checkout-payway/code/control/PayWayHandler.php:268 
[Notice] Undefined index:token
in checkout-payway/code/control/PayWayHandler.php:275

**Comment by andy-knrd** [comment]
All fixed, I had to change the URL to https://www.payway.com.au and used an updated cacerts.crt file from Westpac

**Comment by mlewis-everley** [comment]
Apologies for not getting back on this! I had the same issue at about the same time. Apparently Payway changed their certificate files and for some users this caused an issue (at least it did for me, and by the sound of it, you).
